Package["WolframInstitute`MathNotebook`"]

CopyCellReference::usage = "CopyCellReference[] copies a live, clickable reference to the selected cell to the clipboard."
TagSelectedCell::usage = "TagSelectedCell[] assigns a cell tag to the selected cell, for use as a citation anchor."
GoBack::usage = "GoBack[] moves the selection back to the cell from which the last hyperlink was clicked."
InsertEnvironment::usage = "InsertEnvironment[style] inserts a new cell of the given environment style at the current position."
InsertCitation::usage = "InsertCitation[] inserts a citation link to a tagged reference cell."
ConvertLaTeXCells::usage = "ConvertLaTeXCells[] converts LaTeX math fragments in the selected cells into native typeset math, or in the whole input notebook if nothing is selected.\nConvertLaTeXCells[notebook] converts the given notebook.\nConvertLaTeXCells[{cell, ...}] converts the given cells."
ConvertMathCells::usage = "ConvertMathCells[] converts native typeset math in the selected cells into LaTeX fragments, or in the whole input notebook if nothing is selected.\nConvertMathCells[notebook] converts the given notebook.\nConvertMathCells[{cell, ...}] converts the given cells."
ConvertToMaTeX::usage = "ConvertToMaTeX[] renders the selected display math cells with MaTeX, or all of them if nothing is selected.\nConvertToMaTeX[notebook] converts the given notebook.\nConvertToMaTeX[{cell, ...}] converts the given cells."
ConvertFromMaTeX::usage = "ConvertFromMaTeX[] converts the selected MaTeX-rendered cells back to native typeset math, or all of them if nothing is selected.\nConvertFromMaTeX[notebook] converts the given notebook.\nConvertFromMaTeX[{cell, ...}] converts the given cells."
InstallMaTeX::usage = "InstallMaTeX[] installs and configures the MaTeX paclet."
OpenMaTeXPreferences::usage = "OpenMaTeXPreferences[] opens the user init.m file in the front end, creating it with a MaTeX preferences template if absent."
SetDocumentFontSize::usage = "SetDocumentFontSize[size] scales the prose of the input notebook so that Text is the given font size, on screen and in print.\nSetDocumentFontSize[notebook, size] scales the given notebook.\nSetDocumentFontSize[notebook, Automatic] removes the override."
SetMathFontSize::usage = "SetMathFontSize[size] scales displayed mathematics and equation numbers of the input notebook to the given font size, re-rendering MaTeX cells.\nSetMathFontSize[notebook, size] scales the given notebook.\nSetMathFontSize[notebook, Automatic] removes the override."
ResetDocumentView::usage = "ResetDocumentView[] returns the input notebook to its stylesheet defaults, leaving no trace of the view overrides.\nResetDocumentView[notebook] resets the given notebook."
InstallLaTeXFonts::usage = "InstallLaTeXFonts[] installs Latin Modern and TeX Gyre OpenType fonts from the local TeX Live distribution."
$MathNotebookCloudVersion::usage = "$MathNotebookCloudVersion is the paclet version published in the Wolfram Cloud, or Missing[\"CloudUnreachable\", ...] when the version marker cannot be read."
OpenTutorial::usage = "OpenTutorial[] opens a copy of the MathNotebook tutorial notebook."
$LastHyperlinkCell::usage = "$LastHyperlinkCell is the cell from which the last hyperlink was clicked."
